### ISSUE TITLE
Pose estimation linear regressor?

### ISSUE THREAD

**Issue by hengck23** [ashafaei/dense-depth-body-parts#2]
In the paper[1] (section IV.c), It is mentioned that pose estimation is performed using linear regressor. Where can I find the code and trained model for the linear regressor? Thanks a lot! 

[1]  A. Shafaei, J. J. Little. Real-Time Human Motion Capture with Multiple Depth Cameras. In 13th Conference on Computer and Robot Vision, Victoria, Canada, 2016.

**Comment by ashafaei** [comment]
@hengck23 
This repository is for the dense depth segmentation part of the paper. The linear regression part requires multiple externally calibrated cameras to work. The steps to recreate the results is fairly simple.

- Run the depth segmentation on each person mask for each camera.
- Project the depth into a point cloud and merge all the point clouds with the external calibration parameters and color each particle according to the most likely class that you've retrieved from this deep network.
- Calculate the median (x, y, z) for each class in the merged point cloud and concatenate these statistics into a single feature vector.
- Apply ridge regression to the features to learn the (x, y, z) of each target joint.

You can use the hard-pose set of the [UBC3V dataset](https://github.com/ashafaei/ubc3v) to learn a regression model. It provides everything you'll need.

**Comment by hengck23** [comment]
Thank you for the reply. Let say the median of the N points are put into the vector m=[m1 m2 ...mN]. To predict the k-th point, do you use (1) or  (2) below:
1) predict_k = [m1 m2 ...mN] * regressor
2) predict_k = [m1 m2 ...mN | exclude mk ] * regressor

**Comment by ashafaei** [comment]
@hengck23 
I'm not sure what is it exactly that you mean, but hopefully, the following would disambiguate the matter.

Once you label all the points in your merged point-cloud, you'll end up with something like this.

![alt text](https://raw.githubusercontent.com/ashafaei/ubc3v/master/metadata/sample_merged.png)

Now, this is colored according to the groundtruth, but if you use the output of the deep network as the basis for coloring, you'll get something similar. Note that, at this stage we have no definition for the target skeleton. What we're looking at is merely an intermediate representation upon which we'd build the next block in the pipeline (the regression part). So you can have any target skeleton definition and you can still use this output.

For each class _c_, we have a set of points P_c in our merged point cloud (the points that have the same color). Find the median point in the set P_c. Once you concatenate all the medians you'd end up with a feature vector X \in R^{129} (43 classes times the 3 dimensions of the median).

Now for each target joint J = (X_j, Y_j, Z_j), and for each dimension _separately_, find a W vector \in R^{129} to make the prediction using ridge regression. If you have 13 target joints, you'll need to learn 13*3 = 39 W vectors. The prediction would be the dot product between the feature X and the W vector for each joint and axis.

If you want to squeeze every bit of information, you can augment the feature vector with more statistics than just the median. If I remember correctly, the feature vector that I use at the end for the paper has around 1000 dimensions.

**Comment by Ellenisawake** [comment]
@ashafaei May I know how you actually merged point clouds from different views? I could only get it for each individual view and found out that they are in different reference coordinate. And what os exactly the "mapper" in the  matlab code?

**Comment by ashafaei** [comment]
@Ellenisawake , You need to calibrate the cameras to determine the extrinsic relationship between their point clouds. Each camera needs a 3x3 rotation matrix and a 3x1 translation vector; alternatively, you can represent the 3x3 matrix and the 3x1 vector as a 4x4 matrix. The common method to calibrate cameras is to use the ICP algorithm and its variants ([see this](http://pointclouds.org/documentation/tutorials/iterative_closest_point.php)). Once you determine the extrinsic parameters for your specific camera setting, you can transform each individual point cloud to a reference coordinate system. If you have static depth cameras, you only need to calculate the rigid transformation once.

I provide this parameter in my [UBC3V dataset](https://github.com/ashafaei/ubc3v), and [Berkeley MHAD dataset](http://tele-immersion.citris-uc.org/berkeley_mhad) also provides this in [their demo](http://tele-immersion.citris-uc.org/sites/default/files/demo_depth.zip).

In order to generate a point cloud from the depth images, you need the intrinsic camera parameters. `mapper` implicitly includes these parameters and allows you to generate a point cloud from the depth image. If `I(x, y)` denotes the depth value at `(x, y)` then the point cloud for that pixel would be
```
z = I(x, y);
x = I(x, y) * mapper(x, y).x;
y = I(x, y) * mapper(x, y).y;
```

After you get all the XYZs you need to apply the corresponding transformation to move everything to the reference coordinate system.

**Comment by Ellenisawake** [comment]
@ashafaei Thank you for the detailed explanation!
I used the camera extrinsics in the ground truth file you provided in the dataset. Still I found the point clouds for the 3 views are not aligned. 
In generate_cloud_camera.m you did some transformation to map the angular rotation values from Maya coordinate to Kinect coordinate, do you mean that the Kinect space here would be the global reference coordinate? How bout translation? Any transformation required?

**Comment by ashafaei** [comment]
@Ellenisawake 
Could you please share the path of the sample where the resulting point cloud is misaligned? Are you using the UBC3V toolkit for reconstruction?

I did this nearly a year ago, some of the smaller details may have escaped my memory. 
Looking at the code in [generate_cloud_camera.m](https://github.com/ashafaei/ubc3v/blob/master/process/generate_cloud_camera.m) I can see that each camera structure has a translation parameter (Lines 30 and 62) as well as rotation parameters. This configuration is inside the `.mat` file inside each folder of the dataset. The `.mat` file also includes the posture of the character.

What reference coordinate system you chose is irrelevant, as long as it is consistent. I'm simply using _a_ reference system which I believe should be consistent.

If you still have questions on this, please consider opening an issue inside the corresponding repository here https://github.com/ashafaei/ubc3v/issues.

Thanks.

**Comment by Ellenisawake** [comment]
@ashafaei 
I think I may have made some silly mistakes in my experiment. I tried again and it worked. Thanks a lot!

**Comment by hengck23** [comment]
@ashafaei
Thank you for the explanation. Now I can make the regressor. Thaks again!
